### ISSUE TITLE
Add unique constraint and a smoke test to check that addresses are unique

### ISSUE THREAD

**Issue by aldavidson** [ministryofjustice/postcodeinfo#139] opened 2016-03-07 14:47 UTC
We have previously found an edge case whereby an issue with the addressbase import managed to create 2 copies of each address (including duplicated UPRN) 

We should:
1) add a unique constraint to the address table on UPRN
2) add a smoke test to check that address results for a given postcode contain no duplicates

**Comment by cliffxuan** [comment] 2016-12-19 17:11
@aldavidson, i'm asked by @KamalaHB to work on postcodeinfo this week

1. `Address.uprn` is already a primary key, so it should be unique already. 
2. do you remember which post code it is? so we can use it for the smoke test.

**Comment by aldavidson** [comment] 2016-12-19 17:16
@cliffxuan  It's an obscure issue to do with the particular way we import the data - it's a lot of data (~29m addresses) so we do a few architectural tricks to make it work in a reasonable amount of time (around 4hrs IIRC). Probably easiest if I come and talk to you in person tomorrow morning?

**Comment by cliffxuan** [comment] 2016-12-19 17:26
sure. that'll be good. let's have a chat tomorrow.

**Comment by cliffxuan** [comment] 2016-12-22 17:26
summary of the chat with Al.

it's a very weird problem. in theory it shouldn't happen, as uprn is a primary key, which should be unique always. when it happens, it's more likely a bug with postgres. also when it happens, all the post code has duplicates, so a smoke test with 20 is probably sufficient to expose the problem.

i'm not able to reproduce it yet. let's close it but keep an eye on it.

**Closed by cliffxuan** 2016-12-22 17:26 UTC
